//
//  OpeningBook.swift
//  KataGo Anytime
//
//  Catalog + storage for the downloadable KataGo opening books (6x6...9x9,
//  Japanese-like variant). Mirrors `NeuralNetworkModel`, but downloaded books
//  live in Application Support (excluded from iCloud backup) rather than
//  Documents, because they are large and re-downloadable. The decompressed
//  `.kbook` cache stays in Caches (written by `BookLookup`).
//

import Foundation

public struct OpeningBook: Identifiable, Equatable, Sendable {
    public let id = UUID()
    public let boardSize: Int
    public let title: String
    public let description: String
    /// Download URL of the compact `.kbook.gz` (built from the katagobooks.org
    /// HTML book via scripts/build_book_db.py and published to a GitHub release).
    public let url: String
    public let fileName: String
    /// Compressed download size in bytes (the published books-v1 asset size),
    /// shown in the picker.
    public let fileSize: Int
    /// Komi the book was generated for (Japanese-like rules), informational.
    public let komi: Float

    public init(boardSize: Int,
                title: String,
                description: String,
                url: String,
                fileName: String,
                fileSize: Int,
                komi: Float) {
        self.boardSize = boardSize
        self.title = title
        self.description = description
        self.url = url
        self.fileName = fileName
        self.fileSize = fileSize
        self.komi = komi
    }

    public static func book(forBoardSize size: Int) -> OpeningBook? {
        allCases.first { $0.boardSize == size }
    }

    // Assets published by the KataGoBooks repo's build-books workflow to the
    // `books-v1` release. Each `url` ends with the matching fileName.
    private static let releaseBase =
        "https://github.com/ChinChangYang/KataGoBooks/releases/download/books-v1/"

    public static let allCases: [OpeningBook] = [
        .init(
            boardSize: 6,
            title: "6×6 Opening Book",
            description: """
A near-complete 6×6 opening book under Japanese-like rules (komi 3), with full \
symmetry and transposition handling. Generated by KataGo and published at \
https://katagobooks.org/. When downloaded, the book's candidate moves and \
their evaluations can be shown directly on the board.
""",
            url: releaseBase + "book6x6jp-20230525.kbook.gz",
            fileName: "book6x6jp-20230525.kbook.gz",
            fileSize: 13_507_481,
            komi: 3
        ),
        .init(
            boardSize: 7,
            title: "7×7 Opening Book",
            description: """
A deep 7×7 opening book under Japanese-like rules (komi 8), with full symmetry \
and transposition handling. Generated by KataGo and published at \
https://katagobooks.org/. When downloaded, the book's candidate moves and \
their evaluations can be shown directly on the board.
""",
            url: releaseBase + "book7jpb40s9435-20210806.kbook.gz",
            fileName: "book7jpb40s9435-20210806.kbook.gz",
            fileSize: 38_982_778,
            komi: 8
        ),
        .init(
            boardSize: 8,
            title: "8×8 Opening Book",
            description: """
A large 8×8 opening book under Japanese-like rules (komi 9), with full symmetry \
and transposition handling. Generated by KataGo and published at \
https://katagobooks.org/. This is a sizable download. When downloaded, the \
book's candidate moves and their evaluations can be shown directly on the board.
""",
            url: releaseBase + "book8jpb40s9854-20211114.kbook.gz",
            fileName: "book8jpb40s9854-20211114.kbook.gz",
            fileSize: 191_447_438,
            komi: 9
        ),
        .init(
            boardSize: 9,
            title: "9×9 Opening Book",
            description: """
A very large, deep 9×9 opening book under Japanese-like rules (komi 6), with \
full symmetry and transposition handling. Generated by KataGo and published at \
https://katagobooks.org/. This is a large download. When downloaded, the book's \
candidate moves and their evaluations can be shown directly on the board.
""",
            url: releaseBase + "book9x9jp-20260226.kbook.gz",
            fileName: "book9x9jp-20260226.kbook.gz",
            fileSize: 240_027_267,
            komi: 6
        )
    ]
}

// MARK: - Storage

extension OpeningBook {
    #if DEBUG
    /// Test-only override for the books directory so unit tests don't touch real
    /// app data. Never set in production.
    nonisolated(unsafe) public static var _booksDirectoryOverride: URL?
    #endif

    /// `Application Support/<bundleID>/OpeningBooks/`. Large, re-downloadable
    /// assets belong here (not Documents), and the directory is excluded from
    /// iCloud backup by `ensureBooksDirectory()`.
    public static func booksDirectory() -> URL {
        #if DEBUG
        if let override = _booksDirectoryOverride { return override }
        #endif
        let fm = FileManager.default
        let base = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let bundleID = Bundle.main.bundleIdentifier ?? "KataGoAnytime"
        return base
            .appendingPathComponent(bundleID, isDirectory: true)
            .appendingPathComponent("OpeningBooks", isDirectory: true)
    }

    /// Create the books directory if needed and mark it excluded-from-backup.
    /// `Downloader` does not create directories, so call this before downloading.
    @discardableResult
    public static func ensureBooksDirectory() throws -> URL {
        let dir = booksDirectory()
        let fm = FileManager.default
        if !fm.fileExists(atPath: dir.path) {
            try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        }
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        var mutableDir = dir
        try? mutableDir.setResourceValues(values)
        return dir
    }

    /// The downloaded `.kbook.gz` archive on disk.
    public var downloadedURL: URL {
        OpeningBook.booksDirectory().appendingPathComponent(fileName)
    }

    public var isDownloaded: Bool {
        FileManager.default.fileExists(atPath: downloadedURL.path)
    }

    /// Size in bytes of the downloaded archive, or nil if not downloaded.
    public var onDiskSize: Int? {
        guard let attrs = try? FileManager.default.attributesOfItem(atPath: downloadedURL.path),
              let size = attrs[.size] as? Int else { return nil }
        return size
    }

    /// The decompressed `.kbook` file `BookLookup` writes to Caches, keyed by the
    /// archive name without its `.gz` extension. Removed alongside the archive on
    /// delete so a stale decompressed copy can't linger.
    public var decompressedCacheURL: URL {
        let cacheDir = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
        let name = downloadedURL.deletingPathExtension().lastPathComponent
        return cacheDir.appendingPathComponent(name)
    }

    /// Delete the downloaded archive and its decompressed cache file.
    public func deleteDownloaded() {
        let fm = FileManager.default
        try? fm.removeItem(at: downloadedURL)
        try? fm.removeItem(at: decompressedCacheURL)
    }
}
