name: Build
on:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Xcode build
      run: |
        cd cpp/xcode
        /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/xcodebuild -scheme katago -configuration Release build

    - name: Run Xcode test
      run: |
        cd cpp/xcode
        /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/xcodebuild -scheme katago -configuration Release test
