name: Build
on:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Xcode build
      run: |
        cd cpp/xcode
        /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/xcodebuild -derivedDataPath DerivedData -scheme katago -configuration Release build

    - name: Setup network
      run: |
        mkdir -p models
        cd models
        wget https://github.com/ChinChangYang/KataGo/releases/download/v1.13.2-coreml1/kata1-b18c384nbt-s7709731328-d3715293823.bin.gz
        mv kata1-b18c384nbt-s7709731328-d3715293823.bin.gz model.bin.gz

    - name: Setup CoreML model
      run: |
        mkdir -p models
        cd models
        wget https://github.com/ChinChangYang/KataGo/releases/download/v1.13.2-coreml1/KataGoModel19x19fp16v14s7709731328.mlpackage.zip
        unzip KataGoModel19x19fp16v14s7709731328.mlpackage.zip
        ln -s ../../../../../../models/KataGoModel19x19fp16v14s7709731328.mlpackage ../cpp/xcode/DerivedData/Build/Products/Release/KataGoModel19x19fp16.mlpackage

    - name: Setup test data
      run: |
        ln -s ../../../../../tests cpp/xcode/DerivedData/Build/Products/Release/tests

    - name: Run Xcode test
      run: |
        cd cpp/xcode
        /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/xcodebuild -derivedDataPath DerivedData -scheme katago -configuration Release test
