name: Build
on:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/build.yml'

jobs:
  xcodebuild:
    runs-on: macos-13
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Xcode build
      run: |
        cd cpp/xcode
        /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/xcodebuild -derivedDataPath DerivedData -scheme katago -configuration Release build

    - name: Setup configuration
      run: |
        ln -s ../../../../../configs/misc/coreml_example.cfg cpp/xcode/DerivedData/Build/Products/Release/gtp.cfg

    - name: Setup network
      run: |
        mkdir -p models
        cd models
        wget https://github.com/ChinChangYang/KataGo/releases/download/v1.13.2-coreml1/kata1-b18c384nbt-s7709731328-d3715293823.bin.gz
        ln -s ../../../../../../models/kata1-b18c384nbt-s7709731328-d3715293823.bin.gz ../cpp/xcode/DerivedData/Build/Products/Release/model.bin.gz

    - name: Setup CoreML model
      run: |
        mkdir -p models
        cd models
        wget https://github.com/ChinChangYang/KataGo/releases/download/v1.13.2-coreml1/KataGoModel19x19fp16v14s7709731328.mlpackage.zip
        unzip KataGoModel19x19fp16v14s7709731328.mlpackage.zip
        ln -s ../../../../../../models/KataGoModel19x19fp16v14s7709731328.mlpackage ../cpp/xcode/DerivedData/Build/Products/Release/KataGoModel19x19fp16.mlpackage

    - name: Setup test data
      run: |
        ln -s ../../../../../tests cpp/xcode/DerivedData/Build/Products/Release/tests

    - name: Run Xcode test
      run: |
        cd cpp/xcode
        /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/xcodebuild -derivedDataPath DerivedData -scheme katago -configuration Release test

  cmake-macos:
    runs-on: macos-13
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ninja
      run: |
        brew install ninja

    - name: Setup Xcode
      run: |
        xcode-select -p
        sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer

    - name: Run cmake ninja
      run: |
        cd cpp
        mv CMakeLists.txt-macos CMakeLists.txt
        mkdir build
        cd build
        cmake -G Ninja ../
        ninja

    - name: Run KataGo tests
      run: |
        cd cpp/build
        ./katago runnnlayertests
